# Generated by Django 2.2.5 on 2019-12-23 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_oussema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='oussema',
        ),
    ]
